version: '3.9'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: 'testnest'
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
      MYSQL_ROOT_PASSWORD: testsuperpass
    ports:
      - "3306:3306"
    expose:
      - '3306'
    volumes:
      - mysql-volume:/var/lib/mysql
    restart: always
volumes:
  mysql-volume: